### PR TITLE
Fixes #55

### LINKED ISSUE #55: Test Fixtures need to be cleaned up
Text fixtures appear to be trying to do too much.  The fixture functions should be a short setup of a fixture.  This makes it easy to maintain and understand.  Some of the fixtures are [defining their own classes before deploying them](https://github.com/biologyguy/BuddySuite/blob/f7fe13f68affce3f31350e5862512599f44f2b81/buddysuite/tests/conftest.py#L19-L97).

This class definitions doesn't belong in the fixture setup.  What if we moved it to the test package ```__init__.py``` file?

### PR DESCRIPTION
**Pull request by etiology**
Moves items to the package level

### CODE REVIEW

**Comment by jwbowen** [comment]
Did you fix the issues we ran into earlier today?

**Comment by biologyguy** [comment]
@jwbowen Not yet. I rolled some stuff back so that my environment was working again, which hopefully means it'll work in the Docker env as well, which will hopefully mean it'll work in Travis. Lot's of hopefullys.

**Comment by etiology** [comment]
Yeah it's hard to see if we are introducing more errors since Travis is detecting failure in other areas. One that's handled we can really get into this code base.

**Comment by biologyguy** [comment]
As an added bit of fun. The Docker VM is inflating and I'm almost out of hard drive on my laptop... Alright unimportant stuff, where are you so you can be deleted!

**Comment by biologyguy** [comment]
Hey Todd, can you pull in the most recent commits and confirm that tests pass?

**Pull request closed without merging**
